// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UNC_SelfService_DataAccessAPI_Repository;

#nullable disable

namespace UNC_SelfService_DataAccessAPI_Repository.Migrations.SelfServiceDb
{
    [DbContext(typeof(SelfServiceDbContext))]
    [Migration("20230922135818_Add_RouteScheduleDowntime")]
    partial class Add_RouteScheduleDowntime
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UNC_SelfService_DataAccessAPI_Common.Entities.SelfServiceDb.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("ChangeDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("ChangeUser")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("System");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("CreateUser")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("System");

                    b.Property<string>("Icon")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MenuText")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int?>("ParentMenuItemId")
                        .HasColumnType("int");

                    b.Property<int>("RouteItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentMenuItemId");

                    b.HasIndex("RouteItemId")
                        .HasDatabaseName("IX_MenuItem_RouteItemId");

                    b.ToTable("MenuItem", "SelfService");
                });

            modelBuilder.Entity("UNC_SelfService_DataAccessAPI_Common.Entities.SelfServiceDb.RouteItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ChangeDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("ChangeUser")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("System");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("CreateUser")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("System");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FilePath")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LinkText")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("RequireAuth")
                        .HasColumnType("bit");

                    b.Property<bool>("RequireMfa")
                        .HasColumnType("bit");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SearchDescription")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("Searchable")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("RouteItem", "SelfService");
                });

            modelBuilder.Entity("UNC_SelfService_DataAccessAPI_Common.Entities.SelfServiceDb.RouteItemTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RouteItemId")
                        .HasColumnType("int");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("RouteItemId")
                        .HasDatabaseName("IX_RouteItemTag_RouteItemId");

                    b.ToTable("RouteItemTag", "SelfService");
                });

            modelBuilder.Entity("UNC_SelfService_DataAccessAPI_Common.Entities.SelfServiceDb.RouteScheduleDowntime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Archived")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ChangeDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChangeUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentRoute")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NewRoute")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("RouteItemId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ScheduledOffDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ScheduledOnDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("RouteItemId");

                    b.ToTable("RouteScheduleDowntime", "SelfService");
                });

            modelBuilder.Entity("UNC_SelfService_DataAccessAPI_Common.Entities.SelfServiceDb.MenuItem", b =>
                {
                    b.HasOne("UNC_SelfService_DataAccessAPI_Common.Entities.SelfServiceDb.MenuItem", "ParentMenuItem")
                        .WithMany("ChildMenuItems")
                        .HasForeignKey("ParentMenuItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("UNC_SelfService_DataAccessAPI_Common.Entities.SelfServiceDb.RouteItem", "RouteItem")
                        .WithMany()
                        .HasForeignKey("RouteItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentMenuItem");

                    b.Navigation("RouteItem");
                });

            modelBuilder.Entity("UNC_SelfService_DataAccessAPI_Common.Entities.SelfServiceDb.RouteItemTag", b =>
                {
                    b.HasOne("UNC_SelfService_DataAccessAPI_Common.Entities.SelfServiceDb.RouteItem", "RouteItem")
                        .WithMany("RouteItemTags")
                        .HasForeignKey("RouteItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RouteItem");
                });

            modelBuilder.Entity("UNC_SelfService_DataAccessAPI_Common.Entities.SelfServiceDb.RouteScheduleDowntime", b =>
                {
                    b.HasOne("UNC_SelfService_DataAccessAPI_Common.Entities.SelfServiceDb.RouteItem", "RouteItem")
                        .WithMany()
                        .HasForeignKey("RouteItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RouteItem");
                });

            modelBuilder.Entity("UNC_SelfService_DataAccessAPI_Common.Entities.SelfServiceDb.MenuItem", b =>
                {
                    b.Navigation("ChildMenuItems");
                });

            modelBuilder.Entity("UNC_SelfService_DataAccessAPI_Common.Entities.SelfServiceDb.RouteItem", b =>
                {
                    b.Navigation("RouteItemTags");
                });
#pragma warning restore 612, 618
        }
    }
}
